### ISSUE TITLE
Does not work with Unicode?

### ISSUE THREAD

**Issue by jenokizm** [oodrive/leveldb.net#1]
When I put into the database the values in Russian, then they are replaced with question marks!

sample:
```
db.Put("key3", "привет!");
var keyValue = db.Get("key3");  //??????!
```
I need support UTF8

**Comment by Odirb** [comment]
Hello Jenokizm,
In release 2.1.5 an Encoding parameter have been added in DB constructor (default value is UTF8).

Regards,
Odirb
