### ISSUE TITLE
Failed to add this package in Centos 7.5 with .netcore

### ISSUE THREAD

**Issue by caozen** [oodrive/leveldb.net#4]
Hi all,

I'm using this lib and trying to port my codes to Centos (with .net core 2.1), but failed during add package. (the codes works good in windows)

dotnet add package LevelDB.Stardard returns failed:
error: Unable to find package LevelDB.Stardard. No packages exist with this id in source(s): nuget.org
warn : Package 'LevelDB.Net 1.2.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
error: Package 'LevelDB.Stardard' is incompatible with 'all' frameworks in project '/home/zhcao/testdotnet/testleveldb.csproj'.

dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.401
 Commit:    729b316c13

Runtime Environment:
 OS Name:     centos
 OS Version:  7
 OS Platform: Linux
 RID:         centos.7-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.401/

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  2.2.401 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by Odirb** [comment]
Hi caozen,
This is weird, can you try specifying the version : 
dotnet add package LevelDB.Stardard -v 2.1.6.1

Regards,
Odirb
