### ISSUE TITLE
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'leveldb.dll' or one of its dependencies.

### ISSUE THREAD

**Issue by elijah-potter** [oodrive/leveldb.net#9]
All of a sudden, on all of the new projects I add leveldbnet.standard to, do not work. They throw the exception
```
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'leveldb.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libleveldb.dll: cannot open shared object file: No such file or directory
```
It still works fine on older projects that use the library.

**Comment by VoltaVX** [comment]
Same here

**Comment by plus1998** [comment]
I tried in winform: publish with 'bin/Release/bin/x64'. This dir includes 'leveldb.dll'

**Comment by elijah-potter** [comment]
Guys, I hate to say it, but I don't think `leveldb.net` should be used anymore. The last commit was 5 years ago...
